# Proxy - Renderer
proxy.renderer.host = validator-proxy
proxy.renderer.port = 7015
proxy.renderer.active = true

# Tracker 
tracker.http.host = oaw-dev-tomcat
tracker.http.port = 8080
tracker.http.path = /oaw/services/ValidationDatabaseService?wsdl

# Size Limits (MegaBytes)
pdf.size.limit = 100

server.ssl.key = /opt/usuarios/oaw-validador/config/oaw-validadorTrust.jks
server.ssl.key-store-password = t12341234
server.ssl.key-store-type=JKS
server.ssl.key-alias=validator
server.ssl.enabled-protocols=TLSv1.2